services:
  orchestrator:
    build:
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "${PORT:-9000}:9000"
    volumes:
      - ./Server:/opt/resonance/server
    environment:
      - Orchestrator__LauncherType=Docker
      - Orchestrator__UnityServerDockerContextPath=/opt/resonance/server
