name: "Deploy to server"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Download latest server build
      continue-on-error: true
      run: |
        gh release download --repo isamu-yamazaki/Resonance --pattern ResonanceServer_linux.zip
        mkdir -p Server
        unzip ResonanceServer_linux.zip -d Server
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan ${{ vars.HOST }} >> ~/.ssh/known_hosts

    - name: Remove directory from server
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ vars.USERNAME }}@${{ vars.HOST }} << 'EOF'
          rm -rf ~/${{ vars.DIRECTORY_NAME }}
        EOF

    # Avoid needing to set up SSH access to GitHub for this user
    - name: Transfer repository files to server
      run: |
        scp -i ~/.ssh/id_ed25519 -r ./* ${{ vars.USERNAME }}@${{ vars.HOST }}:~/${{ vars.DIRECTORY_NAME }}

    - name: Deploy on server with Docker
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ vars.USERNAME }}@${{ vars.HOST }} << 'EOF'
          cd ~/${{ vars.DIRECTORY_NAME }}
          docker compose down --remove-orphans
          docker compose up -d --build
        EOF
